### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [DmitryMalkovich/gito-github-client#17]
Would you consider publishing the `.apk` together with the `releases/` here at Github? After all, it's hosted here, and its about Github – so that would be only consequent :) Thanks in advance!

**Comment by DmitryMalkovich** [comment]
@IzzySoft , it will done with all new releases, thanks!

**Comment by IzzySoft** [comment]
Thanks a lot, @DmitryMalkovich – but maybe you could keep this issue open and close it as soon as the first APK has arrived, so I have a signal then when to check for it?
